IMPORT_SCRITP_FILE_NAME = 'ImportApplicationScript'
APPLICATION_TOKEN = '__APPLICATION_TOKEN__'
ADD_APPLICATION_FILE_SCRIPT = f'''
import {APPLICATION_TOKEN}
def getApiClass():
    return {APPLICATION_TOKEN}.{APPLICATION_TOKEN}
'''
