IMPORT_SCRITP_FILE_NAME = 'ImportApplicationScript'
APPLICATION_TOKEN = '__APPLICATION_TOKEN__'
PROJECT_TOKEN = '__PROJECT_TOKEN__'

ADD_APPLICATION_FILE_SCRIPT = f'''
import {PROJECT_TOKEN}
def getApiClass():
    return {PROJECT_TOKEN}.{APPLICATION_TOKEN}
'''
