print-status: False
api:
    name: PythonFramework
    repository :
        dialect: postgresql
        user: user-example
        password: password-example
        host: host-example
        port: 5432
        database: database-example
        url: ${DATABASE_URL}
    extension: yml
    dependency:
        update: False
        list:
            web: [globals,python_helper,python_selenium_helper,swagger_integration_tests,Popen,Path,pygame,numpy,pywin32,SpeechRecognition,PyTTSx,sqlalchemy,psycopg2,webdriver_manager,selenium,pyautogui,pyperclip,wit,twine] ###- pyaudio,python-Levenshtein
            local: [PyAudio-0.2.11-cp38-cp38-win32.whl,python_Levenshtein-0.12.0-cp38-cp38-win32.whl]
    list: [PythonFramework,globals,python_helper,python_selenium_helper,swagger_integration_tests]
    language: EN-US ###- PT-BR ###-
    git:
        url: https://github.com/SamuelJansen/
        extension: git
        PyPI:
            username: samuel.jansen
            password: dns8PyPI*
    basic:
        session:
            key: basic-framework
        api:
            key : python-framework
            project-name: PythonFramework
            class-name: PythonFramework
python:
    version: 3.8
    version-command: python --version
    py-audio:
        install-example:
            64: pip install PyAudio-0.2.11-cp38-cp38-win_amd64.whl ###- example
            32: PyAudio-0.2.11-cp38-cp38-win32.whl ###- example
    link: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyaudio ###- library
